debug: false
server:
  port: 18088
spring:
  redis:
    host: ${public.redis.host} #redis ip地址
    port: ${public.redis.host.port}  #redis端口
    password:  #密码
    database: 1 #库，默认0
    jedis:
      pool:
        max-active: 8     #最大连接数据库连接数，设0为没有限制
        max-wait: -1      #最大建立连接等待时间，如果超过此时间将接到异常，设为-1表示无限制
        max-idle: 8       #最大等待连接中的数量，设0为没有限制
        min-idle: 0       #最小等待连接中的数量，设0为没有限制

  #    cluster:
#      nodes: ${public.spring.redis.cluster.nodes}


  #配置rabbitMq 服务器
  rabbitmq:
    host: ${public.spring.rabbitmq.host}
    port: ${public.spring.rabbitmq.port}
    username: ${public.spring.rabbitmq.username}
    password: ${public.spring.rabbitmq.password}

#  cloud:
#    consul:
#      host: ${public.spring.cloud.consul.host}
#      port: ${public.spring.cloud.consul.port}
#      discovery:
#        register: true
#        serviceName: ${spring.application.name}
#        healthCheckPath: /actuator/health
#        healthCheckInterval: 30s
#        tags: urlprefix-/${spring.application.name}
#        instanceId: ${spring.application.name}:${server.port}
#        prefer-ip-address: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${public.spring.datasource.url}/my_project?characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: ${public.spring.datasource.username}
    password: ${public.spring.datasource.password}