debug: false
server:
  port: 18088
spring:
  redis:
    host: ${public.redis.host} #redis ip地址
    port: ${public.redis.host.port}  #redis端口
    password:  #密码
    database: 1 #库，默认0
    jedis:
      pool:
        max-active: 8     #最大连接数据库连接数，设0为没有限制
        max-wait: -1      #最大建立连接等待时间，如果超过此时间将接到异常，设为-1表示无限制
        max-idle: 8       #最大等待连接中的数量，设0为没有限制
        min-idle: 0       #最小等待连接中的数量，设0为没有限制

  #    cluster:
#      nodes: ${public.spring.redis.cluster.nodes}


#  spring.redis.host=192.168.142.132
#  spring.redis.port=6379
#  # Redis 数据库索引（默认为 0）
#  spring.redis.database=0
#  # Redis 服务器连接端口
#  # Redis 服务器连接密码（默认为空）
#  spring.redis.password=
#  #连接池最大连接数（使用负值表示没有限制）
#  spring.redis.jedis.pool.max-active=8
#  # 连接池最大阻塞等待时间（使用负值表示没有限制）
#  spring.redis.jedis.pool.max-wait=-1
#  # 连接池中的最大空闲连接
#  spring.redis.jedis.pool.max-idle=8
#  # 连接池中的最小空闲连接
#  spring.redis.jedis.pool.min-idle=0
#  # 连接超时时间（毫秒）
#  spring.redis.timeout=0

#  cloud:
#    consul:
#      host: ${public.spring.cloud.consul.host}
#      port: ${public.spring.cloud.consul.port}
#      discovery:
#        register: true
#        serviceName: ${spring.application.name}
#        healthCheckPath: /actuator/health
#        healthCheckInterval: 30s
#        tags: urlprefix-/${spring.application.name}
#        instanceId: ${spring.application.name}:${server.port}
#        prefer-ip-address: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${public.spring.datasource.url}/my_project?characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: ${public.spring.datasource.username}
    password: ${public.spring.datasource.password}