debug: false
server:
  port: 18088
spring:
  redis:
    cluster:
      nodes: ${public.spring.redis.cluster.nodes}

#  cloud:
#    consul:
#      host: ${public.spring.cloud.consul.host}
#      port: ${public.spring.cloud.consul.port}
#      discovery:
#        register: true
#        serviceName: ${spring.application.name}
#        healthCheckPath: /actuator/health
#        healthCheckInterval: 30s
#        tags: urlprefix-/${spring.application.name}
#        instanceId: ${spring.application.name}:${server.port}
#        prefer-ip-address: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${public.spring.datasource.url}/my_project?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: ${public.spring.datasource.username}
    password: ${public.spring.datasource.password}